package it.gristeliti.smartu.utils;

public enum Courses {
    ADVANCED_PROGRAMMING, ALGORITHM_DESIGN, DISTRIBUITED_SYSTEMS, NETWORK_SECURITY,
    ARTIFICIAL_INTELLIGENGE_AND_MACHINE_LEARNING, PROCESS_AND_SERVICES_MODELING_ANALYSIS,
    LARGE_SCALE_DATA_MANAGEMENT
}
